select * from customer

-- Q1. What is the total revenue generated by male vs. female customers?

select gender , sum(purchase_amount) as revenue from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select distinct customer_id,purchase_amount from customer
WHERE discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) as mean from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select TOP 5 item_purchased , round(avg(review_rating),2) as moyenne from customer
group by item_purchased
order by avg(review_rating) DESC

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,round(avg(purchase_amount),2) as mean from customer
where shipping_type IN ('Express','Standard')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,round(avg(purchase_amount),2) as mean ,sum(purchase_amount) as revenue
from customer 
group by subscription_status

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 1.0 
    / COUNT(*) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
case
WHEN previous_purchases =1 THEN 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
END AS Segmentation,
count(*) as counte
from customer
group by
case
WHEN previous_purchases =1 THEN 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
END
order by counte desc;

-- Q8. What are the top 3 most purchased products within each category?
SELECT *
FROM (
    SELECT item_purchased,
           category,
           COUNT(*) AS counte,
           ROW_NUMBER () OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rk
    FROM customer
    GROUP BY item_purchased, category
) st
WHERE rk <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?|
select subscription_status , count(*) as totale from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

select age_group , sum(purchase_amount) as revenue from customer
group by age_group                                               